enable-magisk-update = true
parallel-jobs = 1

[Tok Tok]
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok/"
arch = "arm64-v8a"
build-mode = "module"
version = "latest"
included-patches = "'DownloadsPatch' 'FeedFilterPatch' 'PlaybackSpeedPatch' 'ShowSeekbarPatch' 'RememberClearDisplayPatch' 'SIM Spoof' 'Disable login requirement' 'Fix Google login' 'Settings'"

[IconPackStudio]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/smart-launcher-team/icon-pack-studio/"
