enable-magisk-update = true
parallel-jobs = 1

[TikTok]
enabled = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok/"
arch = "arm64-v8a"
build-mode = "apk"
included-patches = "'Spoof build info'"

[DevCheck]
apkmirror-dlurl = "https://www.apkmirror.com/apk/flar2/devcheck-system-info/devcheck-device-system-info-5-40-release/"
arch = "arm64-v8a"
build-mode = "apk"
included-patches = "'Export all activities' 'Hide ADB status' 'Hide app icon' 'Spoof build info'"
