enable-magisk-update = true
parallel-jobs = 1

[TikTok]
enabled = true
patches-source = "extended"
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok/"
arch = "all"
build-mode = "both"
# Không cần included-patches nếu muốn dùng toàn bộ patch mặc định (khuyến nghị)
