enable-magisk-update = true
parallel-jobs = 1

[TikTok]
enabled = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok/"
arch = "arm64-v8a"
build-mode = "apk"
included-patches = "'Spoof build info'"
