enable-magisk-update = true
parallel-jobs = 1

[TikTok]
enabled = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok/"
arch = "arm64-v8a"
build-mode = "module"
included-patches = "'Spoof build info'"
# Không cần khai báo included-patches để sử dụng toàn bộ patch mặc định mới nhất từ Extended

# Nếu muốn thêm các app khác, có thể bổ sung block cấu hình tương tự bên dưới
